### ISSUE TITLE
Undo broken

### ISSUE THREAD

**Issue by AlexGuo1998** [hneemann/Digital#155] opened 2018-05-29 13:25 UTC
Sometimes `undo` feature would broken. This is rare, about 2 to 3 times last week. I think it happens when editing multiple files.

When this happens, an `undo` command will bring you to a really early state (maybe 20 minutes earlier), and `redo` is not available, so you will lose your recent work.

I'm using Windows 10 64-bit, java 9.0.4 64-bit.

Could you please try to fix this bug? Thanks!

(I'm not a native English speaker, sorry for grammar mistakes)

p.s. Could you please assign a hotkey to single gate step? I think this is really useful when debugging!

p.s.2 On windows, after launching application, `space` would select `new file` rather than `start simulation`, because of key focus. Can this get fixed?

**Comment by AlexGuo1998** [comment] 2018-05-30 00:43
It seems hard to reproduce... I'm trying.

**Comment by hneemann** [comment] 2018-05-31 09:16
@AlexGuo1998 
I'm trying to locate this problem and I expect log files written on your system.
Please look into your home folder! Are there files named "Digital_[date and time].log" similar to "Digital_2018-05-05_12-13-11.log"?
If there are such files, please attach them to this issue.

**Comment by AlexGuo1998** [comment] 2018-05-31 11:49
Yes, there are about 30 logfiles, mostly showing `java.lang.RuntimeException: internal error: Element not found!`
[Digital-logs.zip](https://github.com/hneemann/Digital/files/2058062/Digital-logs.zip)

**Comment by hneemann** [comment] 2018-05-31 13:51
@AlexGuo1998 
It seems to me you have some interesting habits when working on a circuit. :-)
I am not sure if I could fix all the problems.
Please delete all the log files and try the pre release build [v0.18-68-gaa207fb](https://infdigital.dhbw-mosbach.de/).
If new log files are created, please let me know.

**Comment by hneemann** [comment] 2018-06-08 06:03
I closed this issue. But please do not hesitate to reopen it when new problems arise.

**Closed by hneemann** 2018-06-08 06:03 UTC
Labels: bug

**Comment by AlexGuo1998** [comment] 2018-06-08 07:46
OK I see. It seems no problem so far.

**Comment by AlexGuo1998** [comment] 2018-09-08 12:38
@hneemann 
Finally, I got this bug reproduced (maybe).
Add a component, **drag the mouse (important)** to select it, then press `R` to rotate it.
And now, it's done. Undo feature can behave incorrectly from now on.

**Comment by hneemann** [comment] 2018-09-08 13:33
@AlexGuo1998 
Thank you for your efforts. 
It seems to me that there are still some technical debts buried in the event sourcing system.

By the way: I happened to find your video! Nice! :-)

**Comment by nevercast** [comment] 2018-09-09 01:55
@AlexGuo1998 Thanks for reproducing this! Its been bugging me recently but I've been able to find the minimum procedure to reproduce.

**Comment by 3TUSK** [comment] 2019-05-09 20:02
Apologize for reviving an old issue ticket in advance, but recently I have experienced similar glitch. I cannot recall what I have done, but I remember that the undo shortcut caused a large chunk of circuits being reverted and I was unable to recover them by redo them, forcing me to reconstruct everything from scratch manually. Right now, I am still unable to replicate the issue.  
After looking at my home directory, I started to search issue tracker first and found this issue ticket. The issue described in this ticket looks very similar the issue I have experienced, so I decided to follow up this ticket instead of opening a new one.

My environment is the following:

  - OS: macOS High Sierra 10.13.6
  - Java: `OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)`
  - Digital: `Build git-revision v0.22`

Logs & stacktraces generated by Digital:

  - Sample: https://paste.ubuntu.com/p/8pzx4j93qf/
  - All logs generated: [Digital-Logs.zip](https://github.com/hneemann/Digital/files/3163740/Digital-Logs.zip)

Let me know if there is anything else needed.

**Comment by hneemann** [comment] 2019-05-10 15:09
Thank you for your message. I always appreciate such information because it helps me to improve 
Digital. 
All protocols were created in a very short time (approx. 10sec). Was this the only event that caused problems? Or does it happen regularly? You mentioned that you cannot reproduce this problem.  So I expect it to be a single incident?

**Comment by 3TUSK** [comment] 2019-05-10 18:54
Yes, I have not encountered anything similar since then nor before that. Right now I could recall that I most likely pressed Cmd+Z (the undo shortcut) multiple times in a short time interval. I am not familiar with Swing, but I don't think triggering a short cut very quickly is the culprit.
I personally believe it's a single incident as well, but the log suggests me to send this back to Digital issue tracker on GitHub, so I figure it might be worth doing so.

**Comment by hneemann** [comment] 2019-05-10 20:34
@3TUSK 
It was definitely a good idea to send the logs!
I now know that there is a problem that needs to be thought about. I wasn't aware of that before.
