### ISSUE TITLE
Four sided components

### ISSUE THREAD

**Issue by sgparry** [hneemann/Digital#175] opened 2018-07-21 15:11 UTC
NJot highest priority, but could we please have basic four sided components with assignable pin order / number please? It would save having to make a lot of custom shapes designs... could also be used as a basis for quad packages (like the current two sided hapes are to DIL)

**Comment by hneemann** [comment] 2018-07-21 20:05
Is essentially a duplicate of #169, #39

**Closed by hneemann** 2018-07-21 20:05 UTC
