### ISSUE TITLE
Need fix for issues/991 with nod3d

### ISSUE THREAD

**Issue by Johnlon** [hneemann/Digital#1027] opened 2022-09-15 20:46 UTC
I get https://github.com/hneemann/Digital/issues/991 but I've got a hires machine so the workaround exe doesn't work and I need a fixed _nod3d  

Seems this is a bit of a workaround to the font size issue ...

![image](https://user-images.githubusercontent.com/836248/190506476-abddf485-d787-4f60-9592-8c23ca7d8707.png)

**Comment by hneemann** [comment] 2022-09-16 05:50
Duplicate of #991

**Closed by hneemann** 2022-09-16 05:50 UTC

**Comment by Johnlon** [comment] 2022-09-16 12:59
Not sure why this is a dupe of the "Java version" ticket - seems a specific issues to do with Windows and Java gui toolkit.
I've seen the same issue on other products which I why I knew this tweak was a workaround.
