### ISSUE TITLE
Please allow cut and paste into various edit fields

### ISSUE THREAD

**Issue by keller91711** [hneemann/Digital#315] opened 2019-08-21 18:15 UTC
Fields such as attribute values, truth table rows, etc. do not permit cutting and pasting, as most other software does. It would be helpful to allow this. The native OS cut and paste operations could possibly be used.

**Comment by hneemann** [comment] 2019-08-21 19:24
Are there keyboard shortcuts on a mac using the CTRL+[Key] like CTRL+C.
Or is always COMMAND+[Key] used?
Or: Does it work if all CTRL+[Key] shortcuts are replaced by COMMAND+[Key]?

**Comment by keller91711** [comment] 2019-08-21 19:26
It is usually COMMAND + Key:
Command + C = Copy
Command +  X = Cut
Command + V = Paste

**Comment by hneemann** [comment] 2019-08-21 19:31
Duplicate of #302

**Closed by hneemann** 2019-08-21 19:31 UTC
