### ISSUE TITLE
No output connected to a wire ([3; Splitter, In_1; XOr]). The state of the wire is undefined.

### ISSUE THREAD

**Issue by 656e7269717565** [hneemann/Digital#950] opened 2022-04-14 14:36 UTC
I'm doing a circuit that would be capable to encrypt in AES 128, I'm doing a part of the "mixcols" process and this error keeps appearing, how can I fix it
![error](https://user-images.githubusercontent.com/61165048/163413273-f6a0a7bd-9dc7-47e5-8a9b-d09542701129.PNG)

**Comment by hneemann** [comment] 2022-04-14 16:04
could this be a duplicate of #337?

**Comment by 656e7269717565** [comment] 2022-04-14 22:14
so is there a way I can flip the thing or do I have to rethink to make something that would give the same output

**Comment by hneemann** [comment] 2022-04-15 06:27
The splitter at the bottom left appears to have eight inputs and an 8-bit output. 
You can simply configure this splitter to have eight outputs and one 8-bit input.

**Comment by 656e7269717565** [comment] 2022-04-15 17:43
I've designed the other chips with byte i/o, is there a way to split wires because it's going to be a mess to redo everything to make it bit i/o

**Comment by hneemann** [comment] 2022-04-15 17:47
I'm not sure I understood the question, but that is exactly the purpose of the splitter.

**Comment by 656e7269717565** [comment] 2022-04-15 18:01
nevermind, I just realized I could look at one of the chips of an EEPROM to see how it splitted the connections, you shouldn't give the "splitter/merger" that name as it only merges inputs and the name suggests that it could Split inputs (:

**Comment by hneemann** [comment] 2022-04-15 18:19
The splitter is able to split and merge wires:

![z](https://user-images.githubusercontent.com/7190563/163606378-c37e1c83-4b92-4ead-9a84-f66e04c7d509.png)

[z.dig.zip](https://github.com/hneemann/Digital/files/8497420/z.dig.zip)

**Comment by 656e7269717565** [comment] 2022-04-16 02:01
why did I think output splitting meant the number of bits **one** output would have XD, I'm just dumb, anyway thanks for solving my problem xd

**Closed** 2022-04-16 05:20 UTC
Labels: question
