### ISSUE TITLE
Windows 10 Unusable because of graphics glitches

### ISSUE THREAD

**Issue by Surac** [hneemann/Digital#952] opened 2022-04-22 09:50 UTC
version: v0.29

Using the program i discovered graphic gliches on windows 10. When moving the mouse around on dialog windows the graphic gehts broken, even if i close the dialog window. Moving the mouse ober the app window showes "remains" of other gui elements

![image](https://user-images.githubusercontent.com/33027716/164682264-096d6323-c66c-4dea-84fb-70f0b75cff7d.png)

using Java jre-8u331-windows-i586.exe, no Display scaling, using Digital_noD3D.exe

is there a way to make it usable?

**Comment by hneemann** [comment] 2022-04-22 12:17
It appears to be a duplicate of #227.

Please try a more recent version of Java.

**Comment by Surac** [comment] 2022-04-22 14:05
Error is gone with JAVA "jdk-17_windows-x64_bin.exe" from Oracle

p.s. Starting Digital with no SE or JDK installed redirects you to the download page of oracle for Java 8. That was my fault

**Comment by hneemann** [comment] 2022-04-22 18:04
> Starting Digital with no SE or JDK installed redirects you to the download page of oracle for Java 8.

I'm not sure if that was really your fault.

**Closed by hneemann** 2022-04-22 18:04 UTC
