### ISSUE TITLE
Menus break visuals of the simulator

### ISSUE THREAD

**Issue by aXYZGaming** [hneemann/Digital#699] opened 2021-04-08 18:39 UTC
Quite inconsistently, drop-down menus or text boxes completely break the visual aspect of the simulation, making it hard to do anything.

![image](https://user-images.githubusercontent.com/79474483/114079404-73d2f700-98aa-11eb-8b1f-4973924cbe21.png)

**Comment by hneemann** [comment] 2021-04-08 19:00
Are you using Windows 10? In this case this seems to be a duplicate of #227.

**Comment by aXYZGaming** [comment] 2021-04-09 13:55
oh it does now that i look at it...

**Closed** 2021-04-09 14:28 UTC
