### ISSUE TITLE
Clock Control During Simulation

### ISSUE THREAD

**Issue by spdavies** [hneemann/Digital#139] opened 2018-04-19 18:11 UTC
It would be nice to be able to switch clocks during simulation between free-running and controlled by mouse clicks.

**Comment by hneemann** [comment] 2018-04-19 19:10
This is essentially a duplicate of #83.
I do not know your use case, but you can add a breakpoint to your circuit.
So it is possible to run a simulation until a certain condition is met and then you can control the clock by mouse clicks.

**Comment by hneemann** [comment] 2018-04-21 09:29
See #83

**Closed by hneemann** 2018-04-21 09:29 UTC
